name: routine_app_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/welcome-screen-image.png
  image_dark: assets/images/welcome-screen-image.png
  android_12:
    color: "#f7f6f1"
    color_dark: "#272727"
    image: assets/images/welcome-screen-image.png
    image_dark: assets/images/welcome-screen-image.png
  web: false




flutter:


  uses-material-design: true


  assets:
    - assets/images/

